### ISSUE TITLE
machine setup fails on macbook

### ISSUE THREAD

**Issue by mabarnes** [mabarnes/moment_kinetics#183] opened 2024-02-23 09:20 UTC
I am running on a Mac, and In machine setup options, I obtain the following error when entering the julia executable path.

Please enter the path to the Julia executable to be used ['/opt/local/bin/julia']:
> /opt/local/bin/julia
realpath: illegal option -- s
usage: realpath [-q] [path ...]

I can install manually but would be nice to get the script working.  Maybe I'm not understanding something I should be doing?

**Comment by johnomotani** [comment] 2024-02-23 09:22
Looks like a bug caused by `realpath` being different on Mac and Linux. Sorry I didn't have a Mac to test on! Will have a look...

**Comment by mabarnes** [comment] 2024-03-13 12:03
I can confirm that the realpath issue was resolved with the change to the machine-setup-macos branch.  It is now replaced with the error:

Do you want to download, and compile a local version of HDF5 (if you do
not do this, you will be given the option to choose an HDF5 library to
link later)? [y]/n
> 
--2024-03-13 11:55:58--  https://www.hdfgroup.org/package/hdf5-1-14-3-tar-bz2/?wpdmdl=18469
Resolving www.hdfgroup.org (www.hdfgroup.org)... 162.214.184.54
Connecting to www.hdfgroup.org (www.hdfgroup.org)|162.214.184.54|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘hdf5-1.14.3.tar.bz2’

hdf5-1.14.3.tar.bz2                            [ <=>                                                                                   ]   3.76K  --.-KB/s    in 0s      

2024-03-13 11:56:00 (17.8 MB/s) - ‘hdf5-1.14.3.tar.bz2’ saved [3850]

tar: Error opening archive: Unrecognized archive format

I have tried manually unzipping the hdf5-1.14.3.tar.bz2 file, but it does not appear to recognise it as a bzip2 file format.  not sure if this is something mac-specific

**Comment by johnomotani** [comment] 2024-03-13 13:00
I get the same error now when I try to download and compile on Linux, so I suspect it's an issue with the www.hdf5group.org server :-(

**Comment by johnomotani** [comment] 2024-03-13 13:07
They've changed their download link slightly. I'll update this PR to fix. Why they insist trying to force people to download interactively from their web page, I don't know. I have to search through the HTML page source to find the actual download link!

**Comment by johnomotani** [comment] 2024-03-13 13:13
Should be fixed now on #184. I wonder what the next error will be!

**Comment by johnomotani** [comment] 2024-03-13 13:25
Ah, I found a proper download link for HDF5 now! There were a couple of forum threads requesting it from around 2020 that I never found before. It's possible to download both source code and binaries from under
https://support.hdfgroup.org/ftp/HDF5/releases/
which is useful to know :-)

**Closed** 2024-04-08 15:11 UTC
Labels: bug
